const MOCK_TRACKS = [
  {
    id: "track_001",
    title: "Moscow Mule",
    artists: [{ id: "artist_bad_bunny", name: "Bad Bunny" }],
    durationSeconds: 245,
    coverUrl: "cover1.png",
  },
  {
    id: "track_002",
    title: "Tití Me Preguntó",
    artists: [{ id: "artist_bad_bunny", name: "Bad Bunny" }],
    durationSeconds: 244,
    coverUrl: "cover1.png",
  },
  {
    id: "track_003",
    title: "Despechá",
    artists: [{ id: "artist_rosalia", name: "Rosalía" }],
    durationSeconds: 157,
    coverUrl: "cover2.png",
  },
  {
    id: "track_004",
    title: "Todo de Ti",
    artists: [{ id: "artist_rauw", name: "Rauw Alejandro" }],
    durationSeconds: 199,
    coverUrl: "cover2.png",
  },
  {
    id: "track_005",
    title: "Columbia",
    artists: [{ id: "artist_quevedo", name: "Quevedo" }],
    durationSeconds: 197,
    coverUrl: "cover1.png",
  },
  {
    id: "track_006",
    title: "LUNA",
    artists: [{ id: "artist_feid", name: "Feid" }],
    durationSeconds: 214,
    coverUrl: "cover2.png",
  },
  {
    id: "track_007",
    title: "LALA",
    artists: [{ id: "artist_myke", name: "Myke Towers" }],
    durationSeconds: 202,
    coverUrl: "cover1.png",
  },
  {
    id: "track_008",
    title: "Supernova",
    artists: [{ id: "artist_saiko", name: "Saiko" }],
    durationSeconds: 185,
    coverUrl: "cover2.png",
  },
  {
    id: "track_009",
    title: "Memorias",
    artists: [{ id: "artist_mora", name: "Mora" }],
    durationSeconds: 221,
    coverUrl: "cover1.png",
  },
  {
    id: "track_010",
    title: "Quevedo: Bzrp Music Sessions, Vol. 52",
    artists: [
      { id: "artist_bizarrap", name: "Bizarrap" },
      { id: "artist_quevedo", name: "Quevedo" },
    ],
    durationSeconds: 198,
    coverUrl: "cover2.png",
  },
];
